# --- Site basics ---
title: "KB-AI-IMAGE"
description: "کتابخانه‌ی ساخت تصویر با هوش مصنوعی: گایدها، پرامپت‌ها، تمپلیت‌ها و استایل‌ها."
lang: fa
timezone: Asia/Tehran

# اگر ریپو روی GitHub Pagesِ پروژه‌ایه این دو تا رو دقیق کن:
url: "https://wikigoo.github.io"     # دامنه‌ی اصلی (بدون اسلش آخر)
baseurl: "/KB-AI-IMAGE"              # اگر در ریشه است: ""

# --- Theme & Markdown ---
remote_theme: pages-themes/minimal@v0.2.0
markdown: kramdown
kramdown:
  input: GFM

# --- Plugins (whitelist صفحات گیت‌هاب) ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"

# --- Collections (متناسب با پروژه‌ی تو) ---
collections:
  guides:
    output: true
    permalink: /guides/:path/
  prompts:
    output: true
    permalink: /prompts/:path/
  templates:
    output: true
    permalink: /templates/:path/
  styles:
    output: true
    permalink: /styles/:path/

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: post, toc: true }
  - scope: { path: "", type: "guides" }
    values: { layout: doc }
  - scope: { path: "", type: "prompts" }
    values: { layout: doc }
  - scope: { path: "", type: "templates" }
    values: { layout: doc }
  - scope: { path: "", type: "styles" }
    values: { layout: doc }

# --- Assets & performance ---
sass: { style: compressed }
exclude:
  - node_modules
  - vendor
  - README.md
  - .github
  - .vscode

# --- Social/SEO (اختیاری) ---
author:
  name: "Wiki"
  email: "wikigoo58@gmail.com"
logo: /assets/img/logo.png
favicon: /assets/img/favicon.png
seo:
  type: "Website"
  name: "KB-AI-IMAGE"

# --- Project custom vars (برای استفاده در تم/لی‌اوت) ---
kb:
  type: "guide | prompt-library | template | generator | styles"
  last_updated: "2025-08-29"
  see_also:
    - /libraries/...
